version: "2"

services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
    ports:
      - "5433:5432"
    container_name: postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis