version: "2"

services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
    ports:
      - "5434:5432"
    container_name: postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis
    command: --requirepass $REDIS_PASS

  minio:
      image: minio/minio:latest
      ports:
        - "9000:9000"
      environment:
        - MINIO_ROOT_USER=$MINIO_USER
        - MINIO_ROOT_PASSWORD=$MINIO_PASS
      volumes:
        - minio_data:/data
      command: server /data

volumes:
  minio_data: